#springdoc.api-docs.path=/api-docs

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tradedb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
